# Generated by Django 5.0 on 2024-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='catch_copy',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_day',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='img/noImage.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_max',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_min',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tel',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='explanation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
