# Generated by Django 5.0 on 2024-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0002_restaurant_address_restaurant_catch_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='close_day',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default=''),
        ),
    ]
